import type { Metadata } from "next";
import "./globals.css";
import { lexend } from "./ui/font";

export const metadata: Metadata = {
  title: "Credit Card",
  description: "Generated by Credit Card",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lexend.className} antialiased`}
      >
        <div className="z-50 w-screen h-screen flex justify-center items-center">
          {children}
        </div>
        <div className="-z-10 absolute w-screen h-screen flex justify-center items-center bg-no-repeat bg-[url(/Image/background.png)] bg-contain blur-2xl opacity-40 top-0 left-0">
        </div>
      </body>
    </html>
  );
}
